### ISSUE TITLE
todo-list

### ISSUE THREAD

**Issue by Link1986** [Link1986/projet5#3]

**Comment by Link1986** [comment]
- [ ] mise en place du système de cochage/décochage

**Comment by Link1986** [comment]
- [ ] modification de la page d'édition

**Comment by Link1986** [comment]
- [ ] modification de la page de suppression

**Comment by Link1986** [comment]
modification de la page d'édition

**Comment by Link1986** [comment]
- [ ] modification de la page d'édition
